// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAmffbqWvboEQiN4b-vtKro6MPo1hWZM',
    appId: '1:782341238024:web:ccc4dd1fddb1ba9ec590bd',
    messagingSenderId: '782341238024',
    projectId: 'product-searcher-5e109',
    authDomain: 'product-searcher-5e109.firebaseapp.com',
    storageBucket: 'product-searcher-5e109.firebasestorage.app',
    measurementId: 'G-K0QM3DJZ66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT1nllJ-Pt-ymgN0fvaDkGEn8uN_8wzx4',
    appId: '1:782341238024:android:247b2ac6378e7367c590bd',
    messagingSenderId: '782341238024',
    projectId: 'product-searcher-5e109',
    storageBucket: 'product-searcher-5e109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJoX1NKZL43Zvs3nxgfAsk9hHgik_-k3M',
    appId: '1:782341238024:ios:566cb617d23a9d55c590bd',
    messagingSenderId: '782341238024',
    projectId: 'product-searcher-5e109',
    storageBucket: 'product-searcher-5e109.firebasestorage.app',
    androidClientId:
        '782341238024-u5aitt0b322rsd2cgobole6sm9rgbb6g.apps.googleusercontent.com',
    iosClientId:
        '782341238024-q7k9mrj71sh3s85ehi3678cndi3n8g6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.productSearcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJoX1NKZL43Zvs3nxgfAsk9hHgik_-k3M',
    appId: '1:782341238024:ios:566cb617d23a9d55c590bd',
    messagingSenderId: '782341238024',
    projectId: 'product-searcher-5e109',
    storageBucket: 'product-searcher-5e109.firebasestorage.app',
    androidClientId:
        '782341238024-u5aitt0b322rsd2cgobole6sm9rgbb6g.apps.googleusercontent.com',
    iosClientId:
        '782341238024-q7k9mrj71sh3s85ehi3678cndi3n8g6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.productSearcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgAmffbqWvboEQiN4b-vtKro6MPo1hWZM',
    appId: '1:782341238024:web:92b43ed4e490f4bdc590bd',
    messagingSenderId: '782341238024',
    projectId: 'product-searcher-5e109',
    authDomain: 'product-searcher-5e109.firebaseapp.com',
    storageBucket: 'product-searcher-5e109.firebasestorage.app',
    measurementId: 'G-WEQ0N6432F',
  );
}
